### ISSUE TITLE
Messer not displaying incoming messenges.

### ISSUE THREAD

**Issue by wgehalo** [mjkaufer/Messer#137]
### Description

> Messer is not displaying incoming messages. They are present when checking the thread history however. This is on Windows 10 64, using the latest updates as of 12/17/19.

I have tested it on the command prompt, and ps core 6 inside of windows 10's new terminal.

### Steps to Reproduce

1. Install messer following the guide.
2. Login.
3. Have friend send you message.

**Expected behavior:** [What you expect to happen]
Incoming message should display.

**Actual behavior:** [What actually happens]
Incoming message does not display.

### Versions

Run and copy-paste the results of the following:
npm: 6.13.1
node: v13.3.0
messer: 0.7.1

Windows 10, 64 bit.

**Comment by tomquirk** [comment]
Thanks for reporting this @wgehalo, it looks like it could be related to [this issue report on the api we use](https://github.com/Schmavery/facebook-chat-api/issues/763), but I'll check it out.

**Comment by michondr** [comment]
this bug seems to be critical, the same problem has inpact on fb-messenger-cli issued here 
https://github.com/Alex-Rose/fb-messenger-cli/issues/220

**Comment by Ryjekk** [comment]
I have still same issue 

npm: 6.13.1
node: v13.3.0
messer: 0.7.1

macOS Catalina 10.15.4

**Comment by ethan-ou** [comment]
Same issue. It looks like it's because of the API changes Facebook made recently to move messenger to using MQTT (a type of messaging protocol like WebSockets). 

I had a look at the issues in the facebook-chat-api repo as @tomquirk linked and found the library was depreciating its ```api.listen``` method in favour of ```api.listenMqtt``` (see [issue #786 in facebook-chat-api](https://github.com/Schmavery/facebook-chat-api/issues/786)). The change looks to be a drop-in replacement, so it looks like all we'll need to do is change the line in Messer where this API is being used.

I did some testing locally to try this. The ```api.listen``` method is used in the [messen library on line 139](https://github.com/tomquirk/messen/blob/21dc01fa93063678157d1292c7db359c2ca5a56a/src/messen.ts#L139). After changing this line to ```api.listenMqtt```, it looked like incoming messages were being displayed properly.
