### ISSUE TITLE
Commands wont work

### ISSUE THREAD

**Issue by krinklefingers** [mjkaufer/Messer#150]
Every time that I try and run a command of anysort (other than log out) I am met with this error:

> clear
(node:8320) UnhandledPromiseRejectionWarning: TypeError: _repl.clearBufferedCommand is not a function
    at Object.log (/usr/local/lib/node_modules/messer/src/messer/repl.js:21:9)
    at processCommand.then.catch.err (/usr/local/lib/node_modules/messer/src/messer/index.js:115:20)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:8320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I don't really understand why. I can log in an everything but I can't run anything; not clear, not history, nothing. Also, for some reason messer is not saving my token. I have to keep logging in over and over.

**Comment by krunoPeric** [comment]
I also have this issue.  Here's some more information on what I'm seeing:

### Steps to Reproduce

1. `$ sudo apt install npm`
2.  `$ sudo npm install -g messer`
3. `$ messer`
4. now login using your facebook account credentials (the login works successfully)
5. `> contacts`

**Expected behavior:** 

Contact list is printed.

**Actual behavior:** 

the following error is the output:

>(node:8332) UnhandledPromiseRejectionWarning: TypeError: _repl.clearBufferedCommand is not a function
    at Object.log (/usr/local/lib/node_modules/messer/src/messer/repl.js:21:9)
    at processCommand.then.catch.err (/usr/local/lib/node_modules/messer/src/messer/index.js:115:20)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:8332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Versions

- npm -v:  `3.5.2`
- node -v:  `v8.10.0`
- messer -v:  `0.7.2`

**Operating System Version:**
- lsb_release -d:  `Description:	Ubuntu 18.04.4 LTS`
- uname -r: `5.3.0-59-generic`

### Additional Information
It doesn't matter what I type in for the command -- any text input produces the same error.

**Comment by tomquirk** [comment]
Thanks for reporting @krunoPeric. I suspect it's because you're running node@8.10 and `clearBufferedCommand` wasn't supported then. @krinklefingers, I would be interested in your node version as well!

We will have to test every node version to determine what we support, and then make a note of this in the documentation 👍

**Comment by krunoPeric** [comment]
Thanks for the prompt response!  I uninstalled node and installed the lastest LTS binaries:

* node -v: `v12.18.1`

*it's working now :)*

**Comment by tomquirk** [comment]
@krunoPeric nice! I'm running node 12 as well. I think given node 12 is LTS, we are fine to note this in the readme. I'll go and do just that!

**Comment by tomquirk** [comment]
Done! https://github.com/mjkaufer/Messer/releases/tag/v0.7.3
